all:
  vars:
    control_plane_endpoint: 10.10.10.100
    load_balancer_ip_pool:
    - 10.10.10.14/27
metal:
  children:
    masters:
      hosts:
        metal0: { ansible_host: 10.10.10.110, mac: '00:23:24:d1:f5:69', disk: sda, network_interface: eno1 }
        metal1: { ansible_host: 10.10.10.111, mac: '00:23:24:d1:f3:f0', disk: sda, network_interface: eno1 }
        metal2: { ansible_host: 10.10.10.112, mac: '00:23:24:e7:04:60', disk: sda, network_interface: eno1 }
    # workers:
    #   hosts:
    #     metal3: {ansible_host: 192.168.1.113, mac: '00:23:24:d1:f4:d6', disk: sda, network_interface: eno1}
